# permissions for end users to view legacyapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: legacyapp-viewer-role
rules:
- apiGroups:
  - operator.jeantsai.cn
  resources:
  - legacyapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.jeantsai.cn
  resources:
  - legacyapps/status
  verbs:
  - get
